### ISSUE TITLE
Not getting sounds for <cr> and <bs>

### ISSUE THREAD

**Issue by rwmitchell** [lifepillar/vim-keysound#1]
All other sound work except for <cr> and <bs>.  This is my configuration:

`" Typewriter sounds
  let g:keysound = {
        \ 'default':     [
        \   'typewriter-sounds/key001.mp3',
        \   'typewriter-sounds/key002.mp3',
        \   'typewriter-sounds/key003.mp3',
        \  ],
        \ "\<BS>":       ['typewriter-sounds/key001.mp3'],
        \ "\<CR>":       ['typewriter-sounds/return003.mp3'],
        \ 'InsertLeave': ['typewriter-sounds/ding000.mp3'],
        \ 'InsertEnter': ['typewriter-sounds/return001.mp3'],
        \ }
`
or has  screenshot:

![image](https://github.com/lifepillar/vim-keysound/assets/15944841/b643cdd6-d1d2-449a-adc8-9f6d59e849db)

This is the output from :KeySoundDebug

![image](https://github.com/lifepillar/vim-keysound/assets/15944841/0dbb60c3-8d46-40cf-8d7e-0aa79575a07f)

This is using MacVim, but terminal vim works the same.

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Sep 25 2023 07:39:20)
macOS version - x86_64
Included patches: 1-1897

Any idea what I've got wrong?

**Comment by lifepillar** [comment]
Yes (thanks for posting the output of `KeysoundDebug`). In your setup, `<cr>` and `<bs>` are already mapped in Insert mode: see the section “CONFLICTING MAPPINGS”. When a key is already mapped, KeySound does not override the existing mapping (the section “KEYS MAPPED BY KEYSOUND” shows you that KeySound has not defined any mapping).

You may check who has defined a mapping as follows:

```
:verbose imap <cr>
:verbose imap <bs>
```

Resolving conflicts is left to the user. If you post the output of the commands above, I may try to suggest a possible way to work around the conflict.

**Comment by lifepillar** [comment]
It should be possible, but I need to push an update. Let me figure out the best way to do that.

**Comment by lifepillar** [comment]
Please pull the current master. Add this in your `vimrc`:

```vim
let g:AutoPairsMapCR = 0
let g:AutoPairsMapBS = 0

inoremap <expr> <plug>keysoundCR  keysound#PlaySoundFor("\<cr>")
inoremap <expr> <plug>keysoundBS  keysound#PlaySoundFor("\<bs>")
inoremap <expr> <plug>autopairsBS AutoPairsDelete()

imap <cr> <plug>keysoundCR<plug>AutoPairsReturn
imap <bs> <plug>keysoundBS<plug>autopairsBS
```

**Comment by lifepillar** [comment]
This example has been added to the help file. See `:help keysound-conflicts` and `:help keysound.PlaySoundFor()`.

**Comment by rwmitchell** [comment]
Great!  That works flawlessly!

Of course, the very next thing I tried, it failed - too many plugins.  *sigh*

This was a .txt file with:

```
i  <CR>        *@xolox#notes#cleanup_list()
        Last set from ~/.vim/ftplugin/notes.vim line 118
i  <CR>          <Plug>keysoundCR<Plug>AutoPairsReturn<Plug>cleanup_list
        Last set from ~/git/rc/.vim/init/settings.vimrc line 194
```

I tried adding cleanup_list, as you can see in the above, but that didn't work.

I also have a feature suggestion; two layers of sounds that can be enabled/disabled.  For example, having sounds for events, such as BufWritePost, SwapExists, FileChangedShellPost, are useful all the time whereas keyclicks during input mode may want be silenced at times.

Prior to your much more robust method, I was just doing

```
  autocmd SwapExists    * call sound_playfile( g:sound."/femalevoice/fail/Warning.mp3" )
```

I've moved all of my previous setup to your method, but now disabling keystrokes turns off everything.  I knew that was going to happen and can disable the keystrokes easily enough in my settings, but interactively toggling sets would be awesome.)

Thanks for making this available!  And my comments above are by no means a request for anything.  I'm happy the way everything is currently.

**Comment by lifepillar** [comment]
With the current master, you may set `g:keysound_toggle_event_sounds = 0` to keep event sounds playing even when KeySound is off.

**Comment by rwmitchell** [comment]
Thanks!  It'll be a few days before i get a chance to try it. Currently in ICU after having open heart surgery yesterday.

**Comment by rwmitchell** [comment]
I'm using MacVim.  It appears the ```echomsg '[KeySound] On'``` gets echoed to the terminal and not the editor.
This is obviously not a vim-seysound issue, i'm just a little surprised.  Maybe a config issue as I'm loading this via .vimrc and not .gvimrc

I checked my settings and don't see anything obvious where echomsg is remapped to echoc

**Comment by rwmitchell** [comment]
The change I asked about works perfectly!  For me, key003.wav and key010.wav for default sound ideal.

**Comment by lifepillar** [comment]
>I'm using MacVim. It appears the echomsg '[KeySound] On' gets echoed to the terminal and not the editor.

That's very unusual.

> Maybe a config issue as I'm loading this via .vimrc

What is “this”?

**Comment by rwmitchell** [comment]
"this" is the vim-seysound settings, but apparently I have the settings duplicated in both (it's been a couple weeks) and have updated both (now).    The issue with '[KeySound] On' going to the terminal remains.  This still must be a local issue to my setup.
