### ISSUE TITLE
sound_playfile() function may not play mp3 files with libcanberra

### ISSUE THREAD

**Issue by veotos** [lifepillar/vim-keysound#2]
Sound implementation for Linux/Unix using libcanberra does not play mp3 files (only wav files and ogg/vorbis files are mandatory in the [Sound Theme Specification](http://0pointer.de/lennart/projects/libcanberra/#overview)).

My simple workaround is to convert mp3 files to wav and use them:
`ffmpeg -i input.mp3 output.wav `

**Comment by lifepillar** [comment]
Thanks for reporting that! I've changed the format of the sounds to WAV.

**Comment by veotos** [comment]
Thanks to you!
